### ISSUE TITLE
请问有详细的使用教程吗？

### ISSUE THREAD

**Issue by xuzongbao** [maguowei/starred#13]
请问有详细的使用教程吗？我对这个比较感兴趣，但是用不来

**Comment by maguowei** [comment]
你无法使用的主要问题是什么呢？是Python环境不熟悉还是命令参数不清楚怎么使用？ @xuzongbao

**Comment by xuzongbao** [comment]
哦，原来是基于python的，这个没学过。。。。

**Comment by maguowei** [comment]
@xuzongbao 主流的Linux发行版和 Mac 都会默认包涵Python, 如果是Windows环境需要自行下载和安装Python https://www.python.org/downloads/ 。 建议使用Python3.5最新版, 官网下载的安装包默认应该包含包管理工具pip, 然后按照 https://github.com/maguowei/starred/blob/master/README.md 的示例使用即可。

**Comment by xuzongbao** [comment]
@maguowei 也就是说我需要有个本地服务器是吧

**Comment by maguowei** [comment]
@xuzongbao 准确的说是安装Python解释器，https://www.python.org/downloads/

**Comment by xuzongbao** [comment]
@maguowei 好的，谢谢
