### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by AshikNesin** [maguowei/starred#2]
I'm not sure whether its problem in my system or your code. Just want to let you know that I'm getting this error.

![image](https://cloud.githubusercontent.com/assets/4201088/16708354/26980460-460e-11e6-8b4c-48647a6efa9b.png)

**Comment by steakknife** [comment]
Fixed in #4

**Comment by steakknife** [comment]
Actually, it's fixed in master but another similar bug popped up, fixed in #5.
