### ISSUE TITLE
使用3.6的python版本报错

### ISSUE THREAD

**Issue by xiaoyueyue165** [maguowei/starred#25]
````
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f468' in position                                                50: illegal multibyte sequence
````
我看了楼主之前关闭的，有这个错误，是否无法解决？

````
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfqfmfQOQGwO28byj9ux3HXACiW3yWCO94S9SyiXWnLWgTrXfsWJuCYjMM 165800216@qq.com
````
我的github的公钥长这样，设置了几次老是说不对，去前，去后，只留中间或是全部，我不确定设置上了没有，我有85个star，读取出来的README只有10多个

**Comment by maguowei** [comment]
@xiaoyueyue165 
1. 不是ssh 公钥，https://github.com/settings/tokens  看这里生成 Personal access tokens。

2. 关于编码错误的问题。你用的是否是Windows？请尝试在终端中设置: set PYTHONIOENCODING=UTF-8  看是否可以解决。

**Comment by 1132719438** [comment]
加上`set PYTHONIOENCODING=UTF-8`可以
```
set PYTHONIOENCODING=UTF-8 & starred --username 1132719438 --sort > README.md
```

**Comment by yu-liang-zheng** [comment]
在cmd命令终端，加上`set PYTHONIOENCODING=UTF-8`可以解决。
在git bash，加上还是会报错。
