### ISSUE TITLE
ImportError: cannot import name VERSION

### ISSUE THREAD

**Issue by zhongweili** [maguowei/starred#35]
After installed, I met this when running starred:

ImportError: cannot import name VERSION

I don't know whether it's a bug.

Then I edited starred.py, fix it by modifying VERSION to '2.4.1'.

Anyway, thanks for your job. Starred is cool!

**Comment by JKirchartz** [comment]
I have the same issue,

```
Traceback (most recent call last):
  File "/usr/local/bin/starred", line 7, in <module>
    from starred.starred import starred
  File "/usr/local/lib/python2.7/site-packages/starred/starred.py", line 10, in <module>
    from starred import VERSION
ImportError: cannot import name VERSION
```
I replaced line 10 of /usr/local/lib/python2.7/site-packages/starred/starred.py with this:

    # from starred import VERSION
    VERSION = '2.0.4'

and now it works - although I'm sure this hack will be overridden if I were to try to update.

**Comment by maguowei** [comment]
for Python2.x users
```bash
pip install starred==2.03
```
start from v2.04 Python2.x support removed.  https://github.com/maguowei/starred/releases

I will update REDEMD later.
