### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f525' in position 55: illegal multibyte sequence

### ISSUE THREAD

**Issue by SaulNoble** [maguowei/starred#44]
**UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f525' in position 55: illegal multibyte sequence**
这个怎么解决呀。。

**Comment by SaulNoble** [comment]
我的步骤 在powershell窗口中输入
set PYTHONIOENCODING=UTF-8 "&" starred --username saulnoble --sort > README.md

报错：

>  'gbk' codec can't encode character '\u2207' in position 64: illegal multibyte sequence^C

**Comment by teetteet** [comment]
I have the same failure. Any chance to remove any emojis from the description?

**Comment by anlzou** [comment]
运行：starred --username anlzou --sort > StarList.md
        
报错：
    ......
    File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\click\utils.py", line 260, in echo
        file.write(message)
    UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f62e' in position 60: illegal multibyte sequence
        
解决如下：
    utils.py->echo()函数中添加该代码：message = message.encode("utf-8")

问题不大，等我PR一下。 @SaulNoble
