### ISSUE TITLE
Add options to sort based on repository tags

### ISSUE THREAD

**Issue by jwlodek** [maguowei/starred#55]
It would be nice if we could also have starred be able to retrieve and sort repos by their tags. Something like being able to search all repos that have `tui` as a tag. A lot of awesome lists are sorted by categories like this instead of just by language.

**Comment by maguowei** [comment]
will support by csv format

**Comment by maguowei** [comment]
https://github.com/maguowei/starred/commit/b7821f8a17f3b5e09480017bfde1e0e6d44edda9

use latest version with new `--topic` option
`pip install starred==4.2.0`

`starred --username xxx  --token xxx  --repository my-stars --sort --topic
`
example: https://github.com/maguowei/awesome-stars/blob/master/topics.md
