### ISSUE TITLE
Is there anyway to avoid awesome-stars commit in github contributions.

### ISSUE THREAD

**Issue by sudeepdino008** [maguowei/starred#67]
I don't think people would want automated commits to appear in their github contributions. Is there anyway to remove these commits from the contributions and activities?

<img width="779" alt="Screenshot 2021-11-05 at 2 07 43 PM" src="https://user-images.githubusercontent.com/1736155/140482108-6905633d-09a2-4184-a0c9-a6371115fe92.png">

**Comment by maguowei** [comment]
![截屏2021-11-12 上午10 05 14](https://user-images.githubusercontent.com/7894483/141396362-ce1a4810-6ff9-4cca-a4e6-38066b5ce45a.png)

change:
secrets.DAILY_GITHUB_TOKEN  ->  secrets.GITHUB_TOKEN

commits will be record by github-action 
![截屏2021-11-12 上午10 07 43](https://user-images.githubusercontent.com/7894483/141396562-3eb7a7db-0372-4d55-9199-052c44366096.png)
