### ISSUE TITLE
Stars Lists

### ISSUE THREAD

**Issue by mehdichaouch** [maguowei/starred#88]
Hello @maguowei,
I saw that you use Stars List, and me too.
Do you check how to managed those list with your script?

**Comment by maguowei** [comment]
by search: https://github.com/search?p=1&q=%22Generated+by+starred%22&type=Code
by topics: 
- https://github.com/topics/starred
- https://github.com/topics/awesome-stars

**Comment by mehdichaouch** [comment]
Sorry, I was not clean enough, when I talked about stars list, I mean:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/861701/167314876-8630b780-2a3a-4096-87b1-7ee1b560609e.png">
like [here](https://github.com/maguowei?tab=stars)
or
<img width="912" alt="image" src="https://user-images.githubusercontent.com/861701/167314903-2fc97832-c4d9-4866-8176-49f0efaec301.png">
like [here](https://github.com/mehdichaouch?tab=stars) not the repository using `starred`.

**Comment by maguowei** [comment]
stars list  are currently in beta. no api. can't do anything until GitHub opens the api.

latest starred version now support repo category by topics: https://github.com/maguowei/awesome-stars/blob/master/topics.md

this may be a temp workaround.

with `--topic` option: 
`starred --username xxx --token xxx --repository my-stars --sort --topic`

**Comment by mehdichaouch** [comment]
Ok, we will see if GH Stars List will continue after beta period.

Thanks for the`--topic`, I saw that from your last modification :wink:
