### ISSUE TITLE
template: workflow run: `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by montchr** [maguowei/starred#98]
I just generated a new repo from the template and ran the workflow for the first time. The job succeeded, but with the following warning annotation from GitHub:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/montchr/stars/actions/runs/3615604727

**Comment by maguowei** [comment]
upgrade `actions/setup-python@v3` -> `actions/setup-python@v4`  can fix it. 
https://github.com/maguowei/awesome-stars/commit/348ff166be27964b0af3a82ef1e6aebab8457341

refs: 
- https://github.com/actions/setup-python/issues/578
